package com.jcb.passbook.presentation.viewmodel.shared

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.jcb.passbook.data.local.database.entities.User
import com.jcb.passbook.data.repositories.UserRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.security.MessageDigest
import javax.inject.Inject

sealed class AuthState {
    object Idle : AuthState()
    object Loading : AuthState()
    data class Success(val userId: Long) : AuthState()
    data class Error(val message: String) : AuthState()
}

@HiltViewModel
class UserViewModel @Inject constructor(
    private val userRepository: UserRepository
) : ViewModel() {

    companion object {
        private const val TAG = "UserViewModel"
    }

    private val _user = MutableStateFlow<User?>(null)
    val user: StateFlow<User?> = _user.asStateFlow()

    private val _authState = MutableStateFlow<AuthState>(AuthState.Idle)
    val authState: StateFlow<AuthState> = _authState.asStateFlow()

    init {
        Log.d(TAG, "UserViewModel initialized")
        loadUser()
    }

    private fun loadUser() {
        viewModelScope.launch {
            try {
                userRepository.getCurrentUser().collect { currentUser ->
                    _user.value = currentUser
                    if (currentUser == null) {
                        Log.d(TAG, "No user found")
                    } else {
                        Log.d(TAG, "User loaded: ${currentUser.username}")
                    }
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error loading user", e)
            }
        }
    }

    /**
     * ✅ Simple SHA-256 password hashing
     * For production, use BCrypt or Argon2
     */
    private fun hashPassword(password: String): String {
        return try {
            val digest = MessageDigest.getInstance("SHA-256")
            val hashBytes = digest.digest(password.toByteArray())
            hashBytes.joinToString("") { "%02x".format(it) }
        } catch (e: Exception) {
            Log.e(TAG, "Error hashing password", e)
            password // Fallback (NOT recommended in production)
        }
    }

    /**
     * ✅ Register a new user with password hashing
     */
    fun register(username: String, password: String) {
        viewModelScope.launch {
            try {
                _authState.value = AuthState.Loading
                Log.d(TAG, "Starting registration for user: $username")

                // Check if user already exists
                val existingUser = userRepository.getUserByUsername(username)
                if (existingUser != null) {
                    _authState.value = AuthState.Error("Username already exists")
                    Log.w(TAG, "Registration failed: Username already exists")
                    return@launch
                }

                // Hash the password
                val hashedPassword = hashPassword(password)

                // Create new user entity
                val newUser = User(
                    id = 0, // Auto-generated by database
                    username = username,
                    passwordHash = hashedPassword,
                    createdAt = System.currentTimeMillis()
                )

                // Insert user into database
                val userId = userRepository.insertUser(newUser)
                Log.d(TAG, "User inserted with ID: $userId")

                // Set as current user in preferences
                userRepository.setCurrentUserId(userId.toInt())
                Log.d(TAG, "Current user ID set to: $userId")

                // Update local state
                _user.value = newUser.copy(id = userId)
                _authState.value = AuthState.Success(userId)

                Log.d(TAG, "Registration successful for: $username")
            } catch (e: Exception) {
                Log.e(TAG, "Registration error", e)
                _authState.value = AuthState.Error(e.message ?: "Registration failed")
            }
        }
    }

    /**
     * ✅ Login with password hashing verification
     */
    fun login(username: String, password: String) {
        viewModelScope.launch {
            try {
                _authState.value = AuthState.Loading
                Log.d(TAG, "Attempting login for user: $username")

                // Hash the input password for comparison
                val hashedPassword = hashPassword(password)

                // Authenticate user with hashed password
                val authenticatedUser = userRepository.authenticateUser(username, hashedPassword)

                if (authenticatedUser != null) {
                    _user.value = authenticatedUser
                    _authState.value = AuthState.Success(authenticatedUser.id)
                    Log.d(TAG, "Login successful: ${authenticatedUser.username}")
                } else {
                    _authState.value = AuthState.Error("Invalid credentials")
                    Log.w(TAG, "Login failed: Invalid credentials")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Login error", e)
                _authState.value = AuthState.Error(e.message ?: "Login failed")
            }
        }
    }

    /**
     * ✅ Logout user and clear session
     */
    fun logout() {
        viewModelScope.launch {
            try {
                userRepository.clearCurrentUser()
                _user.value = null
                _authState.value = AuthState.Idle
                Log.d(TAG, "User logged out")
            } catch (e: Exception) {
                Log.e(TAG, "Logout error", e)
            }
        }
    }

    /**
     * ✅ Clear auth state (for UI resets)
     */
    fun clearAuthState() {
        _authState.value = AuthState.Idle
    }
}
